### ISSUE TITLE
FFT Gravity Linear Jeans instability error is too large (and other failed tests)

### ISSUE THREAD

**Issue by ghost** [PrincetonUniversity/athena-public-version#35]
This is more about support than an actual issue, forgive me if this belongs somewhere else.

I'm having trouble running run_tests.py for the Jeans instability. I get the error in the title, and am at a loss as to how I should correct this.

For reference, the following tests fail, while the 54 others pass
    * grav.jeans_3d
    * grav.unstable_jeans_3d_mg
    * pgen.hdf5_reader_parallel
    * scalars.mignone_meridional_1d

I'm running intel compilers on a Fedora 31 machine. It is a mere laptop, not a work machine.

Thanks for this project, Athena++ seems very promising.

**Comment by felker** [comment]
What were the errors for the other tests?

**Comment by ghost** [comment]
### Mignone meridional 1D

```
Mignone 1D meridional test problem, case A
RK3 + xorder=2
Reference L1 errors: Mignone (2014) Table 4, N=[32, 2048]
[0.000217, 7.84e-05, 2.26e-05, 6.07e-06, 1.57e-06, 3.99e-07, 1.01e-07]
Observed Athena++ L1 errors, Nx2=[32, 2048]
[2.17e-04 7.84e-05 2.26e-05 6.07e-06 1.57e-06 3.99e-07 1.01e-07]
Percentage differences relative to reference values
[0.10% 0.00% -0.22% 0.01% 0.02% 0.00% 0.42%]
RK3 + xorder=3
Reference L1 errors: Mignone (2014) Table 4, N=[32, 2048]
[8.76e-05, 9.97e-06, 8.44e-07, 6.41e-08, 4.66e-09, 3.45e-10, 8.17e-11]
Observed Athena++ L1 errors, Nx2=[32, 2048]
[8.79e-05 1.00e-05 8.46e-07 6.43e-08 4.67e-09 3.46e-10 7.15e-10]
Percentage differences relative to reference values
[-0.36% -0.44% -0.24% -0.27% -0.25% -0.39% -775.04%]
Observed Athena++ L1 error is higher than Mignone Table 1 value by > 0.500000%

Mignone 1D meridional test problem, case B
RK3 + xorder=2
Reference L1 errors: Mignone (2014) Table 4, N=[32, 2048]
[0.00473, 0.00147, 0.000435, 0.000115, 2.88e-05, 7.14e-06, 1.75e-06]
Observed Athena++ L1 errors, Nx2=[32, 2048]
[4.73e-03 1.47e-03 4.35e-04 1.15e-04 2.88e-05 7.14e-06 1.75e-06]
Percentage differences relative to reference values
[0.08% 0.34% 0.01% 0.10% -0.17% 0.03% -0.27%]
RK3 + xorder=3
Reference L1 errors: Mignone (2014) Table 4, N=[32, 2048]
[0.00257, 0.000587, 0.00013, 2.81e-05, 6.1e-06, 1.33e-06, 2.84e-07]
Observed Athena++ L1 errors, Nx2=[32, 2048]
[2.57e-03 5.86e-04 1.31e-04 2.81e-05 6.10e-06 1.33e-06 2.84e-07]
Percentage differences relative to reference values
[-0.14% 0.13% -0.39% 0.16% -0.07% 0.30% -0.14%]
scalars.mignone_meridional_1d test: prepare(), run(), analyze() finished

Results:
    scalars.mignone_meridional_1d: failed; time elapsed: 358 s

Summary: 0 out of 1 test passed

Traceback (most recent call last):
  File "run_tests.py", line 309, in <module>
    main(**vars(args))
  File "run_tests.py", line 177, in main
    raise TestError()
__main__.TestError
```

### Jeans 3D
```
zone-cycles = 14024704
cpu time used  = 1.8102571000000001e+01
zone-cycles/cpu_second = 7.7473547818152455e+05
1.63763e-06 2.68109e-08
1.63763e-06 1.63763e-06 1.63763e-06
2.68109e-08 2.68107e-08 2.68107e-08
Linear wave error is too large for MG gravity 1.63763e-06
grav.jeans_3d test: prepare(), run(), analyze() finished

Results:
    grav.jeans_3d: failed; time elapsed: 1.2e+03 s

Summary: 0 out of 1 test passed

Traceback (most recent call last):
  File "run_tests.py", line 309, in <module>
    main(**vars(args))
  File "run_tests.py", line 177, in main
    raise TestError()
__main__.TestError

```

### HDF5 Reader Parallel
```
mpicxx  -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180 -c src/mesh/amr_loadbalance.cpp -o /home/Feanor/Athena/athena-public-version/tst/regression/obj/amr_loadbalance.o
src/inputs/hdf5_reader.cpp(94): error: identifier "H5Pset_fapl_mpio" is undefined
        H5Pset_fapl_mpio(property_list_file, MPI_COMM_WORLD, MPI_INFO_NULL);
        ^

src/inputs/hdf5_reader.cpp(109): error: identifier "H5Pset_dxpl_mpio" is undefined
        H5Pset_dxpl_mpio(property_list_transfer, H5FD_MPIO_COLLECTIVE);
        ^

mpicxx  -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180 -c src/mesh/mesh_refinement.cpp -o /home/Feanor/Athena/athena-public-version/tst/regression/obj/mesh_refinement.o
mpicxx  -O3 -std=c++11 -ipo -xhost -inline-forceinline -qopenmp-simd -qopt-prefetch=4 -qoverride-limits -diag-disable 3180 -c src/mesh/meshblock_tree.cpp -o /home/Feanor/Athena/athena-public-version/tst/regression/obj/meshblock_tree.o
compilation aborted for src/inputs/hdf5_reader.cpp (code 2)
make: *** [Makefile:99: /home/Feanor/Athena/athena-public-version/tst/regression/obj/hdf5_reader.o] Error 2
```

**Comment by felker** [comment]
- The HDF5 error is due to a problem with how your HDF5 library is built; this is not an issue with Athena++.
- The remaining errors are all due to about an order of magnitude larger errors than the reference thresholds. 

`1.63763e-06` vs. ` 1.e-7 ` for multigrid and `7.15e-10` vs. `8.17e-11` for the meridional advection problem at the highest resolution, 2048 zones. 

I would not worry too much about the latter violation, since it can be finicky with different compiler optimizations at high resolution. However, I would guess that your Jeans errors might be problematic, since all the FFT configurations produce an error of `2.68109e-08`, much less than the reference threshold `5.0e-4` (right @changgoo?).

What is your CPU model? Do these problems occur with GCC and/or Clang?

**Comment by tomidakn** [comment]
The public version does not include the Multigrid solver yet. I should have removed grav.unstable_jeans_3d_mg test scirpt. So please ignore it.

**Comment by felker** [comment]
Ah, of course; I completely forgot. 

Closing this, since I don't think the discrepancy in the Mignone test is unexpected. We can reopen it if you have true FFT errors.
